# Generated by Django 6.0.6 on 2026-06-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner (No prior experience)'), ('intermediate', 'Intermediate (1-3 years experience)'), ('advanced', 'Advanced (3+ years experience)')], default='beginner', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Any message or questions for the instructor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
