# Generated by Django 5.0.14 on 2026-06-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, help_text='Optional description of the video')),
                ('youtube_url', models.URLField(help_text='Paste standard YouTube link: https://www.youtube.com/watch?v=...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
